import polib

translations = {
    # --- base.html ---
    "Admin Dashboard": "Panel de Administración",
    "Order Builder": "Creador de Pedidos",
    "Receiving": "Recepción",
    "Shipping": "Envíos",
    "History": "Historial",
    "Change Password": "Cambiar Contraseña",
    "Logout": "Cerrar Sesión",
    "Login": "Ingresar",
    "Current Password": "Contraseña Actual",
    "New Password": "Nueva Contraseña",
    "Confirm New Password": "Confirmar Nueva Contraseña",
    "Cancel": "Cancelar",
    "Save Changes": "Guardar Cambios",

    # --- welcome.html ---
    "La Cesta - Café Local": "La Cesta - Café Local",
    "The centralized restaurant requisition management system.": "El sistema centralizado de gestión de requisiciones para restaurantes.",
    "Login\n        to Continue": "Ingresar",
    "Login to Continue": "Ingresar",

    # --- login.html ---
    "Username": "Usuario",
    "Password": "Contraseña",

    # --- admin_dashboard.html ---
    "Admin Dashboard": "Panel de Administración",
    "System Settings": "Configuración del Sistema",
    "Requisition ETA (Business Days)": "ETA de Requisición (Días Hábiles)",
    "Default Language": "Idioma Predeterminado",
    "English": "Inglés",
    "Spanish": "Español",
    "Save Settings": "Guardar Configuración",
    "Organization": "Organización",
    "Catalog": "Catálogo",
    "Users & Logs": "Usuarios y Registros",
    "NPS Survey Setup": "Configuración NPS",
    "Settings": "Configuración",
    "Production Plants": "Plantas de Producción",
    "Plant Name": "Nombre de la Planta",
    "Add": "Agregar",
    "restaurants": "restaurantes",
    "Disable": "Deshabilitar",
    "Enable": "Habilitar",
    "Restaurants": "Restaurantes",
    "Name": "Nombre",
    "Location": "Ubicación",
    "No Production Plant": "Sin Planta de Producción",
    "Unassigned": "Sin asignar",
    "Product Groups": "Grupos de Productos",
    "Group Name": "Nombre del Grupo",
    "Products": "Productos",
    "No Group": "Sin Grupo",
    "Bulk Import Products:": "Importación Masiva:",
    "Download Template": "Descargar Plantilla",
    "Upload CSV": "Subir CSV",
    "Users": "Usuarios",
    "Username": "Usuario",
    "Password": "Contraseña",
    "Select Role": "Seleccionar Rol",
    "Admin": "Administrador",
    "Restaurant": "Restaurante",
    "Production Plant": "Planta de Producción",
    "Requisition User": "Usuario de Requisición",
    "NPS User": "Usuario de NPS",
    "Assign Restaurant": "Asignar Restaurante",
    "Assign Plant": "Asignar Planta",
    "Reset Pwd": "Restablecer",
    "Recent Audit Logs": "Registros de Auditoría",
    "Time": "Hora",
    "Action": "Acción",
    "Entity": "Entidad",
    "Details": "Detalles",
    "NPS Survey Questions": "Preguntas Encuesta NPS",
    "Define the questions customers will see. The Receipt Number is always asked first.": "Defina las preguntas de la encuesta. El número de recibo siempre es obligatorio.",
    "Question Text": "Texto de la Pregunta",
    "Score (0-10)": "Puntuación (0-10)",
    "Yes / No": "Sí / No",
    "Open Text": "Texto Libre",
    "Customer Phone": "Teléfono Cliente",
    "Customer Email": "Correo Cliente",
    "Order": "Orden",
    "Add Question": "Agregar Pregunta",
    "Question": "Pregunta",
    "Type": "Tipo",
    "Actions": "Acciones",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Delete": "Eliminar",
    "Visual Identity": "Identidad Visual",
    "Brand Name": "Nombre de Marca",
    "Primary Color": "Color Primario",
    "Logo URL": "URL del Logo",
    "Enter the public URL of your logo (PNG/JPG recommended).": "Ingrese la URL pública de su logo (PNG/JPG).",
    "Terms and Conditions URL": "URL de Términos y Condiciones",
    "Link to your data treatment and privacy policies.": "Enlace a sus políticas de privacidad.",

    # --- restaurant_order.html ---
    "Daily Requisition Builder": "Constructor de Requisiciones Diarias",
    "Requisition Date": "Fecha de Requisición",
    "Filter by Product Group": "Filtrar por Grupo de Producto",
    "All Groups": "Todos los Grupos",
    "Status": "Estado",
    "Submitted by": "Enviado por",
    "Shipped by": "Enviado por",
    "Closed by": "Cerrado por",
    "Delivery ETA": "Tiempo estimado de entrega",
    "Calculating...": "Calculando...",
    "Draft": "Borrador",
    "Submitted": "Enviado",
    "Shipped": "Enviado",
    "Closed": "Cerrado",
    "SKU": "SKU",
    "Product Name": "Nombre del Producto",
    "Unit Measure": "Unidad de Medida",
    "Current Inventory": "Inventario Actual",
    "Required Quantity": "Cantidad Requerida",
    "Edited By": "Editado Por",
    "Save Draft": "Guardar Borrador",
    "Send to Production": "Enviar a Producción",
    "Order for": "Pedido para",
    "has been": "ha sido",
    "Requisitions Report": "Reporte de Requisiciones",
    "Order Date": "Fecha de Pedido",
    "Action By": "Acción por",
    "Total Items": "Total de Artículos",
    "No past requisitions found.": "No se encontraron requisiciones pasadas.",

    # --- production_shipping.html ---
    "Production Plant Shipping": "Envíos Planta de Producción",
    "Filter by Date": "Filtrar por Fecha",
    "Clear Filter": "Limpiar Filtro",
    "No pending requirements found.": "No se encontraron requerimientos pendientes.",
    "Order #": "Pedido #",
    "Date": "Fecha",
    "Current Inv": "Inv. Actual",
    "Required Qty": "Cant. Requerida",
    "Shipped Qty": "Cant. Enviada",
    "Ship Order": "Enviar Pedido",

    # --- welcome.html ---
    "Intelligence for Gastronomy": "Inteligencia para Gastronomía",
    "We empower restaurants with end-to-end operational control and deep behavioral analytics to scale customer satisfaction.": "Empoderamos a los restaurantes con control operacional de extremo a extremo y analítica profunda para escalar la satisfacción del cliente.",
    "Access Platform": "Acceder a la Plataforma",
    "Our Expertise": "Nuestra Experiencia",
    "Operational Excellence & Analytics": "Excelencia Operacional y Analítica",
    "Operations": "Operaciones",
    "End-to-End Requisitions": "Requisiciones de Extremo a Extremo",
    "Complete management of the supply chain. From the restaurant floor to the production plant, ensuring consistency and efficiency in every order.": "Gestión completa de la cadena de suministro. Desde el restaurante hasta la planta de producción, asegurando consistencia y eficiencia en cada pedido.",
    "Real-time Tracking": "Seguimiento en Tiempo Real",
    "Inventory Sync": "Sincronización de Inventario",
    "Intelligence": "Inteligencia",
    "Deep Data Analytics": "Analítica de Datos Profunda",
    "Unlock the secrets of your menu. Market Basket Analysis to detect item correlations, average ticket trends, and restaurant traffic patterns.": "Desbloquee los secretos de su menú. Análisis de Canasta para detectar correlaciones, tendencias de ticket promedio y patrones de tráfico.",
    "Market Basket": "Canasta de Mercado",
    "Traffic Analysis": "Análisis de Tráfico",
    "Customer": "Cliente",
    "POS NPS Management": "Gestión de NPS en POS",
    "Real-time satisfaction measurement at the point of sale. Capture critical guest feedback immediately and turn detractors into promoters.": "Medición de satisfacción en tiempo real en el punto de venta. Capture comentarios críticos de inmediato y convierta detractores en promotores.",
    "Instant Alerts": "Alertas Instantáneas",
    "Digital Surveys": "Encuestas Digitales",
    "Ready to Scale?": "¿Listo para Escalar?",
    "Join the industry leaders using Plateback to optimize their operations and delight their customers.": "Únase a los líderes de la industria que usan Plateback para optimizar sus operaciones y deleitar a sus clientes.",
    "Start Now": "Comenzar Ahora",
    "The intelligent gastronomy platform": "La plataforma de gastronomía inteligente",

    # --- superadmin_dashboard.html ---
    "SuperAdmin Dashboard": "Panel de SuperAdmin",
    "Platform-wide management — all companies.": "Gestión de toda la plataforma — todas las empresas.",
    "Companies": "Empresas",
    "Company Name": "Nombre de la Empresa",
    "domain (e.g. lacesta)": "dominio (ej: lacesta)",
    "Add": "Agregar",
    "restaurants": "restaurantes",
    "users": "usuarios",
    "Admins": "Administradores",
    "Reset Password": "Restablecer Contraseña",
    "Disable": "Desactivar",
    "Enable": "Activar",
    "Admin": "Admin",
    "Quick Links": "Enlaces Rápidos",
    "View All Order History": "Ver Todo el Historial de Pedidos",
    "Add Company Admin": "Agregar Admin de Empresa",
    "Username": "Usuario",
    "admin": "admin",
    "Password": "Contraseña",
    "Cancel": "Cancelar",
    "Create Admin": "Crear Administrador",
    "Reset Admin Password": "Restablecer Contraseña de Admin",
    "Minimum 6 characters": "Mínimo 6 caracteres",
    "Update Password": "Actualizar Contraseña",
    "Error toggling company": "Error al cambiar estado de la empresa",
    "Company": "Empresa",
    "Admin created successfully!": "¡Administrador creado con éxito!",
    "User": "Usuario",
    "Password must be at least 6 characters": "La contraseña debe tener al menos 6 caracteres",
    "Password reset successfully!": "¡Contraseña restablecida con éxito!",
    "Global settings saved!": "¡Configuraciones globales guardadas!",
    "Error saving settings": "Error al guardar configuraciones",

    # --- restaurant_order.html ---
    "Daily Requisition Builder": "Constructor de Requisición Diaria",
    "Requisition Date": "Fecha de Requisición",
    "Filter by Product Group": "Filtrar por Grupo de Producto",
    "All Groups": "Todos los Grupos",
    "Show required only": "Ver solo requeridos",
    "Delivery ETA": "ETA de Entrega",
    "Calculating...": "Calculando...",
    "Save Draft": "Guardar Borrador",
    "Send to Production": "Enviar a Producción",
    "Order for": "Pedido para",
    "has\n                been": "ha sido",
    "Unit Measure": "Unidad de Medida",
    "Current Inventory": "Inventario Actual",
    "Required Quantity": "Cantidad Requerida",
    "Edited By": "Editado Por",
    "Notes\n                for Production Plant": "Notas para Planta de Producción",
    "Requisitions Report": "Reporte de Requisiciones",
    "Order Date": "Fecha de Pedido",
    "Action By": "Acción Por",
    "Total Items": "Total Artículos",
    "Restaurant Notes": "Notas de Restaurante",
    "Production Notes": "Notas de Producción",
    "Receiving Notes": "Notas de Recepción",
    "Please specify at least one required quantity before saving.": "Por favor especifique al menos una cantidad requerida antes de guardar.",

    # --- restaurant_receiving.html ---
    "Restaurant Receiving": "Recepción de Restaurante",
    "No shipped orders found for receiving.": "No se encontraron pedidos enviados para recepción.",
    "Received Qty": "Cant. Recibida",
    "Confirm Receipt": "Confirmar Recepción",
    "Optional annotations upon receipt...": "Anotaciones opcionales al recibir...",

    # --- production_shipping.html ---
    "Production Plant Shipping": "Envíos Planta de Producción",
    "Notes for Restaurant": "Notas para el Restaurante",
    "Optional annotations...": "Anotaciones opcionales...",
    "Ship Order": "Enviar Pedido",
    "Requisition Shipping Report": "Reporte de Envío de Requisición",
    "Date of Requisition": "Fecha de Requisición",
    "ETA": "ETA",
    "Unit": "Unidad",
    "Amount to be Shipped": "Cantidad a Enviar",
    "Dispatched By (Signature)": "Despachado Por (Firma)",
    "Received By (Signature)": "Recibido Por (Firma)",
    "Print Requisition": "Imprimir Requisición",

    # --- reporte_restaurantes.html ---
    "Return to Dashboard": "Volver al Panel",
    "Strategic\n                Sales Infographic": "Infografía Estratégica de Ventas",
    "Analysis of Traffic, Pareto and Ideal Portfolio Structure": "Análisis de Tráfico, Pareto y Estructura de Portafolio Ideal",
    "Upload Sales (CSV)": "Cargar Ventas (CSV)",
    "Select a restaurant...": "Seleccione un restaurante...",
    "CSV File": "Archivo CSV",
    "Upload Data": "Cargar Datos",
    "Strategic Management": "Gestión Estratégica",
    "Exclude Products": "Excluir Productos",
    "Categorize Items": "Categorizar Artículos",
    "Manage POS Products": "Gestionar Productos POS",
    "Disable products to hide them from all reports.": "Desactive productos para ocultarlos de todos los reportes.",
    "Search products...": "Buscar productos...",
    "Done": "Listo",
    "Strategic Categorization": "Categorización Estratégica",
    "Group products into categories and manage exclusions in bulk.": "Agrupe productos en categorías y gestione exclusiones masivamente.",
    "Search by product or category...": "Buscar por producto o categoría...",
    "Save Changes": "Guardar Cambios",
    "Exclude Entire Category": "Excluir Categoría Completa",
    "Product Name (POS)": "Nombre de Producto (POS)",
    "Strategic Product Name": "Nombre Estratégico",
    "Strategic Category": "Categoría Estratégica",
    "Status": "Estado",
    "Ignored": "Ignorado",
    "Active": "Activo",
    "Uncategorized products default to \"Uncategorized\" and are included in reports.": "Productos sin categoría por defecto son \"Sin Categoría\" y se incluyen en reportes.",
    "Uncategorized": "Sin Categoría",
    "Cancel": "Cancelar",
    "Market Basket Analysis": "Análisis de Canasta",
    "Complete list of product correlations detected in your orders.": "Lista completa de correlaciones detectadas en sus pedidos.",
    "Product Pair": "Par de Productos",
    "Frequency": "Frecuencia",
    "Close": "Cerrar",
    "Total Organization": "Total Organización",
    "Product View": "Vista de Productos",
    "Category View": "Vista de Categorías",
    "Order Volume": "Volumen de Pedidos",
    "Average Ticket per\n                        Order": "Ticket Promedio por Pedido",
    "Diners per Table": "Comensales por Mesa",
    "Sales Pareto (Top 10)": "Pareto de Ventas (Top 10)",
    "The 20%% of products that generate 80%% of monetary income.": "El 20%% de los productos que generan el 80%% de los ingresos.",
    "Anchor Products": "Productos Ancla",
    "Traffic generators (Highest quantity sold).": "Generadores de tráfico (Mayor cantidad vendida).",
    "Frequently Bought Together": "Comprados Juntos Frecuentemente",
    "View All": "Ver Todo",
    "Product pairs that appear most often in the same ticket.": "Pares de productos que aparecen más seguido en el mismo ticket.",
    "Strategy Tip": "Tip Estratégico",
    "Use correlations to create \"Combos\" or\n                \"Packages\" that increase your Average Ticket. Place correlated products together on your physical menu\n                to encourage natural upsells.": "Use correlaciones para crear \"Combos\" o \"Paquetes\" que aumenten su Ticket Promedio. Coloque productos correlacionados juntos en su menú para fomentar ventas sugestivas.",
    "Interactive Portfolio Analysis": "Análisis Interactivo de Portafolio",
    "Simulate demand changes and filter by business contribution (ABC).": "Simule cambios en la demanda y filtre por contribución al negocio (ABC).",
    "Filter ABC": "Filtrar ABC",
    "Demand Simulation": "Simulación de Demanda",
    "Item Name": "Nombre del Artículo",
    "ABC Class": "Clase ABC",
    "Actual Revenue": "Ingreso Real",
    "Simulated Revenue": "Ingreso Simulado",
    "Share %%": "Participación %%",
    "Cumulative %%": "Acumulado %%",
    "TOTAL": "TOTAL",
    "Interactive Volume Analysis": "Análisis Interactivo de Volumen",
    "Simulate demand changes based on total units sold (Quantity ABC).": "Simule cambios en la demanda basados en unidades totales vendidas (ABC de Cantidad).",
    "Volume Simulation": "Simulación de Volumen",
    "Actual Quantity": "Cantidad Real",
    "Simulated Quantity": "Cantidad Simulada",
    "TOTAL UNITS": "UNIDADES TOTALES",
    "Strategy:\n                The Ideal Portfolio (Realistic Scenario)": "Estrategia: El Portafolio Ideal (Escenario Realista)",
    "Based on sales correlation and the 80/20 rule, it is recommended to\n                adopt a Realistic Portfolio. This model balances variety for the customer with operational\n                profitability, eliminating \"dead weight\" from the menu.": "Basado en la correlación de ventas y la regla 80/20, se recomienda adoptar un Portafolio Realista. Este modelo equilibra la variedad para el cliente con la rentabilidad operativa, eliminando el \"peso muerto\" del menú.",
    "Category A (Keep 100%%)": "Categoría A (Mantener 100%%)",
    "High rotation and high margin. They are the core of the\n                    business.": "Alta rotación y alto margen. Son el núcleo del negocio.",
    "Category B (Cross-Selling)": "Categoría B (Venta Cruzada)",
    "Medium rotation. They have high purchasing affinity with\n                    anchor products.": "Rotación media. Tienen alta afinidad de compra con los productos ancla.",
    "Category C (Eliminate / Simplify)": "Categoría C (Eliminar / Simplificar)",
    "Low rotation and complicate kitchen operations (waste).": "Baja rotación y complican las operaciones de cocina (desperdicio).",
    "Income Volume (Relative)": "Volumen de Ingresos (Relativo)",
    "Orders": "Pedidos",
    "No correlations found yet.": "No se han encontrado correlaciones aún.",
    "Expand List": "Expandir Lista",
    "Collapse List": "Contraer Lista",
    "No significant correlations found.": "No se encontraron correlaciones significativas.",
    "No items match the selected filters.": "No hay artículos que coincidan con los filtros.",
    "Uploading...": "Cargando...",
    "Processing file, please wait...": "Procesando archivo, por favor espere...",
    "Success! Data loaded correctly.": "¡Éxito! Datos cargados correctamente.",
    "Error uploading file": "Error al cargar el archivo",
    "No products found.": "No se encontraron productos.",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Saving...": "Guardando...",
    "Error saving mappings": "Error al guardar mapeos",

    # --- setup.html ---
    "System Setup Wizard": "Asistente de Configuración del Sistema",
    "Welcome! Since this is the first run, please set the password for the SuperAdmin account to get started.": "¡Bienvenido! Dado que esta es la primera ejecución, por favor establezca la contraseña para la cuenta SuperAdmin para comenzar.",
    "SuperAdmin Password": "Contraseña de SuperAdmin",
    "Confirm Password": "Confirmar Contraseña",
    "Complete Setup": "Completar Configuración",
    "Passwords do not match": "Las contraseñas no coinciden",
    "Setup complete. You can now log in as superadmin.": "Configuración completada. Ahora puede ingresar como superadmin.",

    # --- nps_survey.html ---
    "Customer Satisfaction Survey": "Encuesta de Satisfacción",
    "1. Receipt / Order Number": "1. Número de Recibo / Pedido",
    "To be filled by the waiter/staff.": "A ser llenado por el mesero/staff.",
    "Next": "Siguiente",
    "Optional": "Opcional",
    "Not likely at all": "Nada probable",
    "Extremely likely": "Extremadamente probable",
    "Yes": "Sí",
    "No": "No",
    "Your feedback...": "Sus comentarios...",
    "Back": "Atrás",
    "Submit Feedback": "Enviar Comentarios",
    "Personal Data Treatment Acceptance": "Aceptación de Datos Personales",
    "I accept the treatment of my personal data according to the": "Acepto el tratamiento de mis datos personales según los",
    "Terms and Conditions": "Términos y Condiciones",
    "No additional questions configured.": "No hay preguntas adicionales configuradas.",
    "Thank You!": "¡Gracias!",
    "Start New Survey": "Iniciar Nueva Encuesta",
    "Submitting...": "Enviando...",
    "Please enter the receipt number": "Por favor ingrese el número de recibo",
    "Please select an option": "Por favor seleccione una opción",
    "Please accept the terms and conditions": "Por favor acepte los términos y condiciones",
    "Error:": "Error:",
    "Failed to submit survey": "Error al enviar la encuesta",
    "Connection error": "Error de conexión",

    # --- nps_report.html ---
    "NPS SCORE": "PUNTUACIÓN NPS",
    "PROMOTERS": "PROMOTORES",
    "PASSIVES": "PASIVOS",
    "DETRACTORS": "DETRACTORES",
    "TOTAL RESPONSES": "TOTAL RESPUESTAS",
    "Completed surveys": "Encuestas completadas",
    "Receipt #": "Recibo #",
    "Score": "Puntaje",
    "No survey responses found for the selected filters.": "No se encontraron respuestas para los filtros seleccionados.",
    "All Restaurants": "Todos los Restaurantes",
    "Print": "Imprimir",

    # --- login.html ---
    "Login": "Ingresar",
    "Username": "Usuario",
    "Password": "Contraseña",
    "Waking up system...": "Despertando el sistema...",
    "System is still sleeping. Please try again in a moment.": "El sistema está despertando. Intente de nuevo en un momento.",

    # --- history.html ---
    "History": "Historial",
    "Filter by Date": "Filtrar por Fecha",
    "Clear Filter": "Limpiar Filtro",
    "No past requisitions found.": "No se encontraron requisiciones pasadas.",
    "Order #": "Pedido #",
    "Date": "Fecha",
    "Submitted by": "Enviado por",
    "Shipped by": "Enviado por",
    "Closed by": "Cerrado por",
    "View Details": "Ver Detalles",
    "items": "artículos",
    "Notes from Restaurant": "Notas de Restaurante",
    "Notes from Production Plant": "Notas de Planta de Producción",
    "Receiving Annotations": "Anotaciones de Recepción",
    "SKU": "SKU",
    "Product Name": "Nombre del Producto",
    "Required Qty": "Cant. Requerida",
    "Shipped Qty": "Cant. Enviada",
    "Received Qty": "Cant. Recibida",

    # --- reports / analytics ---
    "Strategic Sales Infographic": "Infografía Estratégica de Ventas",
    "Analysis of Traffic, Pareto and Ideal Portfolio Structure": "Análisis de Tráfico, Pareto y Estructura de Portafolio Ideal",
    "Upload Sales (CSV)": "Cargar Ventas (CSV)",
    "Select a restaurant...": "Seleccionar restaurante...",
    "Upload Data": "Cargar Datos",
    "Strategic Management": "Gestión Estratégica",
    "Exclude Products": "Excluir Productos",
    "Categorize Items": "Categorizar Artículos",
    "Manage POS Products": "Gestionar Productos POS",
    "Disable products to hide them from all reports.": "Deshabilite productos para ocultarlos de los reportes.",
    "Search products...": "Buscar productos...",
    "Strategic Categorization": "Categorización Estratégica",
    "Group products into categories and manage exclusions in bulk.": "Agrupe productos en categorías y gestione exclusiones masivas.",
    "Market Basket Analysis": "Análisis de Canasta (Market Basket)",
    "Complete list of product correlations detected in your orders.": "Lista completa de correlaciones detectadas en sus pedidos.",
    "Product Pair": "Par de Productos",
    "Frequency": "Frecuencia",
    "Sales Pareto (Top 10)": "Pareto de Ventas (Top 10)",
    "The 20% of products that generate 80% of monetary income.": "El 20% de los productos que generan el 80% de los ingresos.",
    "Anchor Products": "Productos Ancla",
    "Traffic generators (Highest quantity sold).": "Generadores de tráfico (Mayor cantidad vendida).",
    "Frequently Bought Together": "Comprados Juntos Frecuentemente",
    "View All": "Ver Todo",
    "Strategy Tip": "Tip de Estrategia",
    "TOTAL": "TOTAL",
    "TOTAL UNITS": "TOTAL UNIDADES",

    # --- Landing Page (welcome.html) ---
    "Intelligence for Gastronomy": "Inteligencia para la Gastronomía",
    "We empower restaurants with end-to-end operational control and deep behavioral analytics to scale customer satisfaction.": "Empoderamos a los restaurantes con control operativo de extremo a extremo y analítica profunda para escalar la satisfacción del cliente.",
    "Access Platform": "Acceder a la Plataforma",
    "Operational Excellence & Analytics": "Excelencia Operativa y Analítica",
    "End-to-End Requisitions": "Requisiciones de Extremo a Extremo",
    "Complete management of the supply chain. From the restaurant floor to the production plant, ensuring consistency and efficiency in every order.": "Gestión completa de la cadena de suministro. Desde el restaurante hasta la planta, asegurando consistencia y eficiencia.",
    "Deep Data Analytics": "Analítica de Datos Profunda",
    "Unlock the secrets of your menu. Market Basket Analysis to detect item correlations, average ticket trends, and restaurant traffic patterns.": "Descubra los secretos de su menú. Análisis de Canasta para detectar correlaciones, tendencias y patrones de tráfico.",
    "POS NPS Management": "Gestión de NPS en Punto de Venta",
    "Real-time satisfaction measurement at the point of sale. Capture critical guest feedback immediately and turn detractors into promoters.": "Medición de satisfacción en tiempo real. Capture comentarios críticos de los invitados de inmediato.",
    "Ready to Scale?": "¿Listo para Escalar?",
    "Join the industry leaders using Plateback to optimize their operations and delight their customers.": "Únase a los líderes de la industria que usan Plateback para optimizar sus operaciones.",
    "Start Now": "Comenzar Ahora",
    "Turn every meal into data-driven insights.": "Convierta cada comida en información basada en datos.",
    "The intelligent customer satisfaction and analytics platform.": "La plataforma inteligente de satisfacción del cliente y analítica.",
    "Get Started": "Comenzar",
    "Learn More": "Saber Más",
    "Everything you need to scale your brand": "Todo lo que necesita para escalar su marca",

    # --- admin_dashboard.html (additional) ---
    "NPS Satisfaction Report": "Reporte de Satisfacción NPS",
    "View Sales Analytics Report": "Ver Reporte de Analítica",
    "NPS Thank You Message": "Mensaje de Agradecimiento NPS",
    "SuperAdmin": "SuperAdmin",
    "Admin Dashboard": "Panel de Administración",
    "History": "Historial",
    "NPS Survey": "Encuesta NPS",

    # --- NPS Survey (additional) ---
    "Customer Satisfaction Survey": "Encuesta de Satisfacción",
    "1. Receipt / Order Number": "1. Número de Recibo / Pedido",
    "To be filled by the waiter/staff.": "A ser llenado por el mesero/staff.",
    "Next": "Siguiente",
    "Optional": "Opcional",
    "Not likely at all": "Nada probable",
    "Extremely likely": "Extremadamente probable",
    "Yes": "Sí",
    "No": "No",
    "Your feedback...": "Sus comentarios...",
    "Back": "Atrás",
    "Submit Feedback": "Enviar Comentarios",
    "Personal Data Treatment Acceptance": "Aceptación de Datos Personales",
    "I accept the treatment of my personal data according to the": "Acepto el tratamiento de mis datos personales según los",
    "Terms and Conditions": "Términos y Condiciones",
    "items": "artículos",
}

po = polib.pofile('translations/es/LC_MESSAGES/messages.po')

matched = 0
unmatched = []

for entry in po:
    if entry.msgid in translations:
        entry.msgstr = translations[entry.msgid]
        matched += 1
    else:
        # Keep existing translation if already set, otherwise flag it
        if not entry.msgstr:
            entry.msgstr = entry.msgid  # Fallback to original
        unmatched.append(repr(entry.msgid))

po.save()
print(f"Done. {matched} translated, {len(unmatched)} unmatched:")
for u in unmatched:
    print(f"  UNMATCHED: {u}")
