INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ACEITE VEGETAL', ' T20', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ACEITE DE OLIVA', 'T21', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ACEITUNA MORADA', '98800', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ACEITUNA VERDE', '34879', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AJONJOLI DESCORTEZADO', 'T130', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AJONJOLI NEGRO', '70112', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ALCAPARRA BABY', '786', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ALMENDRA FILETEADA', 'T167', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AREQUIPE', '5068', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ATUN LATA gANDE', 'T30', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AZUCAR BLANCA', 'T31', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AZUCAR ORGANICA SOBRE', '2333', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AZUCAR PULVERIZADA', 'T33', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CAFÉ PERSONAL', '23459865', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CANELA EN ASTILLAS', '70140', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CLAVO DE OLOR', '5812', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CRANBERRY', 'T138', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ESENCIA DE BANANO', '70211', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('GRANADINA', '7999', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('HUEVOS', 'T121', 'UND ', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('INSTACREM X SOBRE', '8956', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('JALAPENOS', '337', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('JUGO DE CRANBERRY', 'P110', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA GALON', '6511', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MEZCLA PARA PANCAKES', '70212', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MIEL DE ABEJAS ', 'T39', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MIEL MAPPLE', 'T41', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MOSTAZA GALON', '5115', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('NUEZ DEL NOGAL', 'T155', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PANELA ORGANICA', '876', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAPA CALDO', 'S001', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAPA FRANCESA', '70179', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAPRIKA', 'T57', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PEPERONCCINO', 'T59', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PEPINILLO ENELDO * 790 g', '913', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PIMIENTA CAYENA', 'T60', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PIMIENTA NEGRA EN PEPA', 'T62', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SABRO STEVIA', '3338', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SAL REFISAL', '65', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA  CHOCO HERSHEYS', 'T369', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA DE SOYA', '70333', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA DE TOMATE GALON', '6510', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SPLENDA', '3337', 'UND', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('TOMATE SECO', 'T47', 'KG', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('VINAGRE BALSÁMICO', 'T48', 'LITRO', 1, 1, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('VINAGRE BLANCO', 'T178', 'LITRO', 1, 1, 1);
commit;