INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ALCOHOL', 'A-1', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('BOLSA BASURA JUMBO', 'A-2', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('BOLSA BASURA ROJA', 'A-3', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('BOLSA CANECA BARISTA', 'A-4', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('BOLSA PAPELERA BLANCA', 'A-5', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('CLOROX INVAR S-340', 'A-6', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('DESENGRASANTE INVAR S-500', 'A-7', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('DESINCRUSTANTE INVAR S-407', 'A-8', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ESCOBA', 'A-9', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ESPONJA DE BRILLO', 'A-10', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ESPONJA DE LOZA MALLA', 'A-11', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ESPONJA MAGICA', 'A-12', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ESPONJA SABRA Y ESPUMA', 'A-13', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('FABULOSO DESINFECTANTE', 'A-14', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GEL ANTIBACTERIAL', 'A-15', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GUANTES DE ASEO ', 'A-16', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GUANTES DE VINILO', 'A-17', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('JABON ANTIBACTERIAL INVAR S-260', 'A-18', 'LT', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('PALO DE ESCOBAS', 'A-19', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('PAÑOS AZULES LIMPIAR', 'A-20', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('PAPEL HIGIENICO', 'A-21', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TAPABOCAS', 'A-22', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TOALLAS DE MANO ROLLO', 'A-23', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TRAPEROS', 'A-24', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('RECOGEDOR', 'A-25', 'UNI', 9, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('CUCHARAS DESECHABLES', 'E-1', 'UNI', 10, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('CUCHILLOS DESECHABLES', 'E-2', 'UNI', 10, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('PITILLOS', 'E-3', 'UNI', 10, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('SERVILLETAS DE CAFETERIA', 'E-4', 'UNI', 10, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('SERVILLETAS DE LUJO', 'E-5', 'UNI', 10, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TENEDORES DESECHABLES', 'E-6', 'UNI', 10, 1);