INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('CREMA DE LECHE ', 'T1', 'LT', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MANTEQUILLA CAJA X 42 ', '151', 'UND', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MARGARINA LA FINA', '10964', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('SOUR CREAM x 680 g', 'T16', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('YOGURT GRIEGO x 1000 g', 'T17', 'LT', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('YOGURT GRIEGO x 480 g', '9601', 'UND', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO FETA ', 'T7', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO PAIPA DISCO x 100 g', '7097', 'UND', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO PAIPA TAJADO', 'T13', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO PARMESANO', 'T14', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO PRENSADO', 'T15', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO TIPO MOZARELLA BLOQUE', '589', 'KG', 8, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('QUESO TIPO MOZARELLA TAJADO', '589-1', 'KG', 8, 1);