INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MINI TRENZA SALADO', '9630', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MOGOLLA DE AJONJOLI Y NUEZ', 'PS09', 'P*6', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN CIABATTA POSTA', 'T019', 'UND', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN BAGUETTE', '8020', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN BRIOCHE ROLL ', '70108', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN CIABATTA CEBADA', 'T0118', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN DE 7 GRANOS', '70114', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN DE DATILES Y NUEZ', '70118', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN HAMBURGUESA BRIOCHE', '70238', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN HAMBURGUESA DE PANDEYUCA', 'PA-01', 'UND', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PANDEYUCA PANECOOK', 'PA-02', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN MOLDE AVENA CEBADA', 'T8776', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN MOLDE FRANCES 70141', '70141', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN MOLDE SOURDOGH', '70241', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN SOURDOGH DE AVENA', '70113', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN SOURDOGH TRIGO', 'T005', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN DE AJONJOLI Y NUEZ MOLDE', 'PS08', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN DE CENTENO ALMENDRA MOLDE', 'PS06', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN CON FE', 'PA-03', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('QUICHE JAMÓN-QUESO', 'T013', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('QUICHE TOMATE-ALBAHACA', 'T012', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CROISSANT DE ALMENDRAS', '245', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CROISSANT DE CHOCO ALMENDRAS', '246', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CROISSANT DE QUESO', '243', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CROISSANT INTEGRAL ', '9901', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CROISSANT SENCILLO', '212', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PAN DE CHOCOLATE', 'T244', 'UND ', 5, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('TORTA DE ALMOJABANA ', 'PA-04', 'UND ', 5, 1);