INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('ALFAJORES ', 'PS03', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('BROWNIE', '70400', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GALLETA CHIPS DE CHOCOLATE', '70159', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GALLETA DE AVENA Y PASAS', '70160', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GALLETA SPARKLE', '70161', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('GALLETA RED VELVET ', 'PS01', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('LECHE ASADA ', 'PS02', 'UND', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI TORTA ALMOJABANA ', 'PS03-1', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI TORTA RED VELVET', 'PS04', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI TORTA CHOCOLATE', 'PS05', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI TORTA ALMENDRA ', 'PS06', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI TORTA DE ZANAHORIA', 'PS07', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI GALLETAS SPARKLE', 'PS08', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI GALLETA REDVELVET', 'PS09', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI GALLETA DE CHIPS', 'PS10', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('MINI GALLETA AVENA', 'PS11', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('PIE DE MANZANA', '70327', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TORTA DE CHOCOLATE ', '9044', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TORTA RED VELVET', '70185', 'UND ', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TORTA ZANAHORIA FROSTING', '70156', 'UND', 7, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active) values ('TORTA ALMENDRA ', 'PS10', 'UND ', 7, 1);