INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('AREPAS', '9991', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PLATANO CALENTADO x 500g', '9913', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('ARROZ PARBORIZADO FUERTE x125 g', '11.1', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('BASE PARA PIZZETA', '8666', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CALENTADO', '587', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CEBOLLA ENCURTIDA x 500', 'T190', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CHIMICHURRY x 300 g', '5082', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('DEMIGLASS', '', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('EDAMAME COCINADO x 50 g', '7090', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('FONDO DE VERDURAS X 1000 g ', 'T169', 'LITRO', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('FONDO DE POLLO x 1000g', 'S007', 'LITRO', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('FONDO DE RES x 1000g', 'S002', 'LITRO', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('FRIJOL NEGRO x 80 g', '98672', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('GRANOLA', '5025', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('GRANOLA FRASCO', '9005', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('HOGO PARA BISTEC x 180 g', 'T193', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('HOGO PARA HUEVOS x 500 g', 'T192', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LENTEJA PARDINA x 150 g', '8', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAIZ COCINADO  x30 g', '344', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA CHIPOTLE x 300 g', '7033', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA DIJON x 600 g', 'T194', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA LA CESTA x 300 g', '403', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA SIRACHA x 300 g', 'T184', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MAYONESA VERDE x 600 g', '1255', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MERMELADA DE ARANDANOS x 500 g ', '4449', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MERMELADA FRUTOS ROJOS X 500 g', '210', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MERMELADA DE COCO CEBOLLA x 300 g ', 'T020', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MERMELADA DE GUAYABA x 500 g ', '745', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MEZCLA DE PANDEYUCA PARA WAFLES', 'X1', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PESTO DE ALBAHACA x 300 g', 'T205', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PESTO DE TOMATE SECO x 500 g', 'T200', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PURE DE PAPA CRIOLLA ', 'X2', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('QUINUA BLANCA x 150 g', 'T44', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('QUINUA NEGRA x 125g', '5091', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA BECHAMEL x 500 g', '7222', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA DE QUESO PAIPA x 500 g', '5049', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA LOMO MOSTAZA x 400 g', '5008', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA LOMO TRES PIMIENTAS x 400 g', '414', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA MEXICANA x 500 g', 'T301', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA NAPOLITANA x 500 g', '209', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA POLLO MARROQUI x 400 g', '8095', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA POLLO QUESO AZUL x 400 g', '5014', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SALSA TERIYAKI x 400 g', '70225', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SOPA DE VEGETALES x 350 g ', 'T304', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SOPA MEXICANA x 350 g', 'T301', 'UND', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('TAHINE GARBANZO x 300 g', '401', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('VINAGRETA BALSÁMICA x 600 g', 'T185', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('VINAGRETA DE LIMÓN x 1000 g', 'T175', 'KG', 2, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('VINAGRETA MIEL MOSTAZA x 300 g', 'T171', 'KG', 2, 1);
