INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CHOCOLATE NESTLE', 'X3', 'KG', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CHOCOLATE PASTILLA', '5310', 'UNI', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('CHOCOLYNE', '487', 'KG', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('COCOA CORONA', '544', 'KG', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE CONDENSADA', '76340', 'KG', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE DE SOYA', '280', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE DESLACTOSADA', '2', 'KG', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE ENTERA', 'T3', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE EN POLVO', 'T151', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('MILO', '8977', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('LECHE DE ALMENDRAS', '299', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('EXTRACTO DE MANZANA', '70101', 'LITRO', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE FRESA x 1000 g', '5201', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE GUANABANA ', '12563', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE MANGO ', '12674', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE MARACUYA ', '5032', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE MORA', '116', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('PULPA DE PIÑA', '5,034', 'UND', 3, 1);
INSERT INTO requisitions_db.products (name, sku, unit_measure, group_id, is_active, company_id) values ('SYRUP JUGOS', '3568', 'UND', 3, 1);